name: Fetch basic REST API data

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Data Branch
        uses: actions/checkout@v4
        with:
          ref: data

      - name: Fetch Basic Profile
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "User-Agent: REST-API-Bot" \
          "https://api.github.com/users/jrwnnnn" > profile.json

      - name: Fetch Public Repositories
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "User-Agent: REST-API-Bot" \
          "https://api.github.com/users/jrwnnnn/repos?sort=pushed&per_page=100" > repositories.json

      - name: Fetch Recent Events
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "User-Agent: REST-API-Bot" \
          "https://api.github.com/users/jrwnnnn/events?per_page=10" > activity.json

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add profile.json repositories.json activity.json

          if [[ -n $(git status -s) ]]; then
            git commit -m "Update portfolio data [skip ci]"
            git push origin data
          else
            echo "No changes."
          fi
