name: Fetch Participation Data On REST API

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-participation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: data

      - name: Fetch Participation
        run: |
          echo "{}" > participation.json
          repo_names=$(jq -r '.[].name' repositories.json)
          
          for repo in $repo_names; do
            data=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "User-Agent: REST-API-Bot" "https://api.github.com/repos/jrwnnnn/$repo/stats/participation")
            jq --arg r "$repo" --argjson d "$data" '.[$r] = $d' participation.json > temp.json && mv temp.json participation.json
            sleep 1
          done

      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add participation.json
          git diff --staged --quiet || (git commit -m "Update participation.json [skip ci]" && git push origin data)